apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth-deploy-light-private
  namespace: geth
  labels:
    app: geth-light-private
spec:
  selector:
    matchLabels:
      app: geth-light-private # has to match .spec.template.metadata.labels
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: geth-light-private # has to match .spec.selector.matchLabels
    spec:
      volumes:
      - name: geth-keystore-testnet #used for ropsten testnet so named the volumes with testnet
        persistentVolumeClaim:
          claimName: geth-keystore-testnet
      terminationGracePeriodSeconds: 10
      containers:
      - name: geth-light-private
        image: mariobyn/custom-geth:1.10.1-light-private
        imagePullPolicy: Always #you can delete this config, i was using it when developing
        env:
          - name: ADDITIONAL_PARAMS
            value: 
        ports:
        - containerPort: 50505
          name: rpc
        volumeMounts:
          - name: geth-keystore-testnet
            mountPath: /root/.ethereum/testnet/keystore
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "6Gi"
            cpu: "2"
