apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth-deploy-light
  namespace: geth
  labels:
    app: geth-light
spec:
  selector:
    matchLabels:
      app: geth-light # has to match .spec.template.metadata.labels
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: geth-light # has to match .spec.selector.matchLabels
    spec:
      volumes:
        - name: geth-keystore-testnet #used for ropsten testnet so named the volumes with testnet
          persistentVolumeClaim:
            claimName: geth-keystore-testnet
        - configMap:
            name: cm-static-peers
          name: geth-static-peers
      terminationGracePeriodSeconds: 10
      containers:
        - name: geth-light
          image: {{image}}-light
          imagePullPolicy: Always #you can delete this config, i was using it when developing
          env:
            - name: ADDITIONAL_PARAMS
              value:
          ports:
            - containerPort: 50505
              name: rpc
          volumeMounts:
            - name: geth-keystore-testnet
              mountPath: /root/.ethereum/ropsten/keystore
            - name: geth-static-peers
              mountPath: /root/.ethereum/ropsten/geth/static-nodes.json
              subPath: static-nodes.json
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "6Gi"
              cpu: "2"
