apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-chaindata-light-testnet-rinkeby
  namespace: geth
  labels:
    app: geth-light-rinkeby
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp2
  volumeMode: Filesystem
