apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-keystore-testnet
  namespace: geth
  labels:
    app: geth-light
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2-enc # aws encrypted
  volumeMode: Filesystem
