FROM  ethereum/client-go:v1.9.25

ENV GETH_USER root
ENV GETH_PASSWORD $GETH_PASSWORD
ENV GETH_HOME /$GETH_USER
ENV TEST_NET true 
ENV HEIGHT_THRESHOLD 100 
 

RUN apk --update add --no-cache openssh bash  git nodejs nodejs-npm && \
  mkdir monitor && \
  echo "${GETH_USER}:${GETH_PASSWORD}" | chpasswd && \
  rm -rf /var/cache/apk/* && \
  sed -ie 's/#Port 22/Port 3333/g' /etc/ssh/sshd_config && \
  sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config && \
  /usr/bin/ssh-keygen -A

EXPOSE 50505
EXPOSE 3333
EXPOSE 3004 
EXPOSE 6060

ADD docker-entrypoint-light.sh .
RUN chmod a+x /docker-entrypoint-light.sh

ENTRYPOINT ["/docker-entrypoint-light.sh"]

