apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-chaindata-private
  namespace: geth
  labels:
    app: geth-private
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp2
  volumeMode: Filesystem
