apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-ethereum-private
  namespace: geth
  labels:
    app: geth-private
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2-enc # aws encrypted
  volumeMode: Filesystem
